"""Rejestr narzędzi Q API — metadata i słownik TOOLS."""
from __future__ import annotations

from typing import Any

from qbot_tools import (
    _tool_qbot_api_self_check,
    _tool_qbot_api_tools_list,
    _tool_qbot_db_overview,
    _tool_qbot_git_status,
    _tool_qbot_ride_readiness_status,
    _tool_qbot_project_diff_summary,
    _tool_qbot_project_files,
    _tool_qbot_project_guard_check,
    _tool_qbot_project_recent_commits,
    _tool_qbot_project_tree,
    _tool_qbot_query,
    _tool_qbot_recent_tool_calls,
    _tool_qbot_services_status,
    _tool_qbot_status,
    _tool_qbot_system_overview,
)

from qbot_operator_tools import (
    _tool_qbot_error_summary,
    _tool_qbot_operator_runbook,
    _tool_qbot_operator_snapshot,
    _tool_qbot_readiness_report,
    _tool_qbot_tool_usage_summary,
)

from qbot_ops_tools import (
    _tool_qbot_answer_context,
    _tool_qbot_backup_plan,
    _tool_qbot_backup_status,
    _tool_qbot_backup_timer_status,
    _tool_qbot_create_backup_script_preview,
    _tool_qbot_llm_boundary_policy,
    _tool_qbot_logs_overview,
    _tool_qbot_maintenance_report,
    _tool_qbot_operator_final_smoke_test,
    _tool_qbot_operator_quick_reference,
    _tool_qbot_restore_drill_plan,
    _tool_qbot_restore_drill_status,
    _tool_qbot_service_logs,
    _tool_qbot_test_error_classification,
)

from qbot_mcp_adapter import (
    _tool_qbot_mcp_call_preview,
    _tool_qbot_mcp_status,
    _tool_qbot_mcp_tools_list,
)

from qbot_legacy_tools import (
    _tool_qbot_legacy_answer_context,
    _tool_qbot_legacy_error_summary,
    _tool_qbot_legacy_health_report,
    _tool_qbot_legacy_logs,
    _tool_qbot_legacy_status,
)

from qbot_legacy_inventory_tools import (
    _tool_qbot_legacy_capability_scan,
    _tool_qbot_legacy_dependency_inventory,
    _tool_qbot_legacy_entrypoint_inventory,
    _tool_qbot_legacy_file_inventory,
    _tool_qbot_legacy_inventory_answer_context,
    _tool_qbot_legacy_migration_plan,
)

from qbot_legacy_parity_tools import (
    _tool_qbot_artifact_export_preview,
    _tool_qbot_artifact_import_from_file_preview,
    _tool_qbot_artifacts_legacy_status,
    _tool_qbot_artifacts_filesystem_inventory,
    _tool_qbot_external_integrations_report,
    _tool_qbot_garage_legacy_status,
    _tool_qbot_garmin_proxy_status,
    _tool_qbot_garmin_upload_status,
    _tool_qbot_hammerhead_import_status,
    _tool_qbot_legacy_full_parity_audit,
    _tool_qbot_legacy_parity_matrix,
    _tool_qbot_weather_current,
    _tool_qbot_weather_forecast,
    _tool_qbot_weather_status,
    _tool_qbot_weather_legacy_status,
)

from qbot_legacy_wrapper_tools import (
    _tool_qbot_legacy_capability_status,
    _tool_qbot_legacy_export_status,
    _tool_qbot_legacy_garmin_status,
    _tool_qbot_legacy_qlab_status,
    _tool_qbot_legacy_readonly_wrapper_report,
    _tool_qbot_legacy_sync_status,
    _tool_qbot_legacy_wrapper_answer_context,
)

from qbot_legacy_execution_tools import (
    _tool_qbot_legacy_export_dry_run,
    _tool_qbot_legacy_garmin_dry_run,
    _tool_qbot_legacy_qlab_smoke_check,
    _tool_qbot_legacy_safe_execution_answer_context,
    _tool_qbot_legacy_safe_execution_report,
    _tool_qbot_legacy_sync_dry_run,
)

from qbot_legacy_shadow_tools import (
    _tool_qbot_legacy_cutover_plan,
    _tool_qbot_legacy_shadow_answer_context,
    _tool_qbot_legacy_shadow_probe,
    _tool_qbot_legacy_shadow_report,
)

from qbot_legacy_cutover_tools import (
    _tool_qbot_legacy_cutover_answer_context,
    _tool_qbot_legacy_cutover_readiness_gate,
    _tool_qbot_legacy_cutover_status,
    _tool_qbot_legacy_manual_cutover_plan,
    _tool_qbot_legacy_rollback_plan,
    _tool_qbot_legacy_takeover_status,
)

from qbot_llm_planner import (
    _tool_qbot_execute_validated_plan,
    _tool_qbot_llm_plan_query,
    _tool_qbot_llm_provider_status,
    _tool_qbot_llm_run_query,
    _tool_qbot_policy_validate_plan,
    _tool_qbot_tool_policy_list,
)

from qbot_artifact_tools import (
    _tool_qbot_artifact_create,
    _tool_qbot_artifact_get,
    _tool_qbot_artifact_list,
    _tool_qbot_workspace_write_file_preview,
)

from qbot_external_llm_tools import (
    _tool_qbot_chatgpt_decision_record_create,
    _tool_qbot_chatgpt_prompt_pack,
    _tool_qbot_external_context_bundle,
    _tool_qbot_external_llm_policy,
    _tool_qbot_external_llm_status,
    _tool_qbot_external_llm_workflow_guide,
)

from qbot_telegram_tools import (
    _tool_qbot_public_endpoint_status,
    _tool_qbot_telegram_answer_context,
    _tool_qbot_telegram_command_help,
    _tool_qbot_telegram_config_status,
    _tool_qbot_telegram_agent_chat,
    _tool_qbot_telegram_agent_chat_self_check,
    _tool_qbot_telegram_conversation_self_check,
    _tool_qbot_telegram_delete_webhook,
    _tool_qbot_telegram_legacy_audit,
    _tool_qbot_telegram_llm_chat,
    _tool_qbot_telegram_llm_chat_self_check,
    _tool_qbot_telegram_runtime_self_check,
    _tool_qbot_telegram_send_test,
    _tool_qbot_telegram_set_webhook,
    _tool_qbot_telegram_status,
    _tool_qbot_telegram_webhook_plan,
)

from qbot_ops_tools import (
    _tool_qbot_answer_context,
    _tool_qbot_backup_plan,
    _tool_qbot_backup_status,
    _tool_qbot_backup_timer_status,
    _tool_qbot_create_backup_script_preview,
    _tool_qbot_llm_boundary_policy,
    _tool_qbot_logs_overview,
    _tool_qbot_maintenance_report,
    _tool_qbot_operator_final_smoke_test,
    _tool_qbot_operator_quick_reference,
    _tool_qbot_restore_drill_plan,
    _tool_qbot_restore_drill_status,
    _tool_qbot_service_logs,
    _tool_qbot_test_error_classification,
)

from qbot_route_tools import (
    _tool_qbot_csv_export_create_execute,
    _tool_qbot_csv_export_create_preview,
    _tool_qbot_csv_export_inventory,
    _tool_qbot_csv_export_latest_get,
    _tool_qbot_csv_export_status,
    _tool_qbot_hammerhead_config_status,
    _tool_qbot_hammerhead_import_dry_run,
    _tool_qbot_hammerhead_import_inventory,
    _tool_qbot_hammerhead_import_status_enhanced,
    _tool_qbot_hammerhead_restore_plan,
    _tool_qbot_rwgps_config_status,
    _tool_qbot_rwgps_dry_run,
    _tool_qbot_rwgps_legacy_status,
    _tool_qbot_rwgps_restore_plan,
)

from qbot_integration_tools import (
    _tool_qbot_xert_config_status,
    _tool_qbot_xert_readiness_status,
    _tool_qbot_xert_restore_plan,
    _tool_qbot_intervals_config_status,
    _tool_qbot_intervals_wellness_status,
    _tool_qbot_intervals_restore_plan,
    _tool_qbot_garmin_config_status,
    _tool_qbot_garmin_upload_dry_run,
    _tool_qbot_garmin_restore_plan,
    _tool_qbot_cronometer_config_status,
    _tool_qbot_cronometer_legacy_status,
    _tool_qbot_cronometer_restore_plan,
    _tool_qbot_weather_config_status,
    _tool_qbot_openmaps_config_status,
    _tool_qbot_openmaps_legacy_status,
    _tool_qbot_public_web_fallback_self_check,
    _tool_qbot_public_web_fetch,
    _tool_qbot_public_web_status,
    _tool_qbot_resolve_user_location,
    _tool_qbot_weather_current,
    _tool_qbot_weather_forecast,
)

from qbot_garage_tools import (
    _tool_qbot_garage_legacy_file_audit,
    _tool_qbot_garage_import_preview,
    _tool_qbot_garage_import_execute,
    _tool_qbot_garage_raw_status,
    _tool_qbot_garage_raw_list,
    _tool_qbot_garage_raw_get,
    _tool_qbot_garage_raw_search,
)

from qbot_report_tools import (
    _tool_qbot_daily_report_status,
    _tool_qbot_daily_report_preview,
    _tool_qbot_daily_report_send,
    _tool_qbot_ride_report_status,
    _tool_qbot_ride_report_latest,
    _tool_qbot_ride_report_preview,
    _tool_qbot_ride_report_send,
    _tool_qbot_reports_schedule_status,
    _tool_qbot_reports_restore_plan,
)

TOOLS_META: dict[str, dict[str, Any]] = {
    "qbot_status": {
        "description": "Podstawowe informacje o serwerze API (hostname, python, pid)",
        "category": "diagnostic",
        "safe": True,
        "args_schema": {},
    },
    "qbot_services_status": {
        "description": "Status usług systemd: q-bot, qbot-qlab, qbot-api, postgresql",
        "category": "diagnostic",
        "safe": True,
        "args_schema": {},
    },
    "qbot_recent_tool_calls": {
        "description": "Ostatnie N wywołań tooli z historii (limit 1–50)",
        "category": "database",
        "safe": True,
        "args_schema": {"limit": 10},
    },
    "qbot_git_status": {
        "description": "Stan repozytorium Git (/opt/qbot/app): branch, commit, clean",
        "category": "diagnostic",
        "safe": True,
        "args_schema": {},
    },
    "qbot_api_tools_list": {
        "description": "Lista wszystkich dostępnych narzędzi API z metadanymi",
        "category": "meta",
        "safe": True,
        "args_schema": {},
    },
    "qbot_db_overview": {
        "description": "Przegląd bazy danych: wersja PG, licznik tool_calls, statusy",
        "category": "database",
        "safe": True,
        "args_schema": {},
    },
    "qbot_system_overview": {
        "description": "Przegląd systemu: uptime, load, dysk, RAM, statusy usług",
        "category": "diagnostic",
        "safe": True,
        "args_schema": {},
    },
    "qbot_api_self_check": {
        "description": "Zbiorczy autotest API: DB, usługi, git, liczniki",
        "category": "meta",
        "safe": True,
        "args_schema": {},
    },
    "qbot_ride_readiness_status": {
        "description": "Publiczny read-only status endpoint dla QExt2 / Karoo / ride-readiness",
        "category": "diagnostic",
        "safe": True,
        "args_schema": {},
    },
    "qbot_project_tree": {
        "description": "Drzewo katalogów projektu (max_depth 1–4)",
        "category": "project",
        "safe": True,
        "args_schema": {"max_depth": 2},
    },
    "qbot_project_files": {
        "description": "Lista plików projektu z rozmiarem i datą modyfikacji",
        "category": "project",
        "safe": True,
        "args_schema": {},
    },
    "qbot_project_recent_commits": {
        "description": "Ostatnie commity Git (limit 1–30)",
        "category": "project",
        "safe": True,
        "args_schema": {"limit": 10},
    },
    "qbot_project_diff_summary": {
        "description": "Podsumowanie zmian roboczych: status, diff --stat, lista plików",
        "category": "project",
        "safe": True,
        "args_schema": {},
    },
    "qbot_project_guard_check": {
        "description": "Sprawdzenie naruszeń zasad: qbot_qlab, Gate, env, port",
        "category": "project",
        "safe": True,
        "args_schema": {},
    },
    "qbot_query": {
        "description": "Procesor zapytań naturalnych — rozpoznaje intencje i deleguje do narzędzi",
        "category": "meta",
        "safe": True,
        "args_schema": {"query": "sprawdź stan Q"},
    },
    "qbot_error_summary": {
        "description": "Podsumowanie ostatnich błędów z historii tool_calls",
        "category": "operator",
        "safe": True,
        "args_schema": {"limit": 50},
    },
    "qbot_tool_usage_summary": {
        "description": "Statystyka użycia narzędzi: liczba wywołań, statusy, najczęściej używane",
        "category": "operator",
        "safe": True,
        "args_schema": {"limit": 200},
    },
    "qbot_readiness_report": {
        "description": "Ocena gotowości Qbot do pracy: READY, READY_WITH_WARNINGS, NOT_READY",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_operator_snapshot": {
        "description": "Zbiorczy snapshot diagnostyczny — API, system, DB, git, guard, błędy",
        "category": "operator",
        "safe": True,
        "args_schema": {"include_recent_calls": True, "recent_limit": 20},
    },
    "qbot_operator_runbook": {
        "description": "Gotowe operacyjne scenariusze (safe_to_work, full_diagnostic, error_review, project_review, api_review)",
        "category": "operator",
        "safe": True,
        "args_schema": {"name": "safe_to_work", "execute": False},
    },
    "qbot_service_logs": {
        "description": "Bezpieczny odczyt ostatnich logów wybranej usługi z journalctl (allowlista)",
        "category": "operator",
        "safe": True,
        "args_schema": {"service": "qbot-api.service", "lines": 80},
    },
    "qbot_logs_overview": {
        "description": "Szybki przegląd logów wszystkich dozwolonych usług — błędy, ostrzeżenia, próbki",
        "category": "operator",
        "safe": True,
        "args_schema": {"lines": 40},
    },
    "qbot_backup_status": {
        "description": "Sprawdza setup backupów: katalogi, pliki, pg_dump, wiek ostatniego backupu",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_backup_plan": {
        "description": "Bezpieczny plan backupu — komendy do ręcznego wykonania, NIE wykonuje backupu",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_create_backup_script_preview": {
        "description": "Podgląd skryptu backupu do ręcznego zapisania — NIE zapisuje pliku",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_test_error_classification": {
        "description": "Klasyfikacja błędów tool_calls na testowe vs realne problemy",
        "category": "operator",
        "safe": True,
        "args_schema": {"limit": 200},
    },
    "qbot_maintenance_report": {
        "description": "Zbiorczy raport operatorski — readiness, backup, logi, błędy, guard",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_backup_timer_status": {
        "description": "Status systemd timera backupu — czy istnieje, aktywny, następne odpalenie",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_restore_drill_plan": {
        "description": "Plan testowego restore do osobnej bazy — komendy, weryfikacja, bezpieczeństwo",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_restore_drill_status": {
        "description": "Status bazy qbot_restore_drill — czy istnieje, czy ma dane po drill",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_operator_quick_reference": {
        "description": "Ściąga operatora — endpointy, tools, runbooki, checklisty",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_answer_context": {
        "description": "Przygotowuje bezpieczny, zsanitizowany kontekst dla przyszłego LLM answer synthesizer",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"source_tool": "qbot_readiness_report", "source_args": {}},
    },
    "qbot_llm_boundary_policy": {
        "description": "Statyczna polityka granicy LLM — role, ograniczenia, flow",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_operator_final_smoke_test": {
        "description": "Zbiorczy test finalny sprawdzający full operational readiness",
        "category": "operator",
        "safe": True,
        "args_schema": {},
    },
    "qbot_mcp_status": {
        "description": "Status adaptera MCP dla ChatGPT connectora — routing, auth, reachability",
        "category": "mcp",
        "safe": True,
        "args_schema": {},
    },
    "qbot_mcp_tools_list": {
        "description": "Lista publicznych tools MCP i mapowania do tooli QBot",
        "category": "mcp",
        "safe": True,
        "args_schema": {},
    },
    "qbot_mcp_call_preview": {
        "description": "Podgląd mapowania MCP tool → QBot tool bez wykonania",
        "category": "mcp",
        "safe": True,
        "args_schema": {"mcp_tool": "qbot.status", "args": {}},
    },
    "qbot_legacy_status": {
        "description": "Sprawdza stan legacy Q (q-bot.service) — read-only systemctl show",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_logs": {
        "description": "Ostatnie logi q-bot.service z journalctl",
        "category": "legacy",
        "safe": True,
        "args_schema": {"lines": 120},
    },
    "qbot_legacy_error_summary": {
        "description": "Podsumowanie błędów z logów q-bot.service — wzorce error/warning",
        "category": "legacy",
        "safe": True,
        "args_schema": {"lines": 300},
    },
    "qbot_legacy_health_report": {
        "description": "Zbiorczy raport legacy Q — status, błędy, guard, services",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_answer_context": {
        "description": "Zsanitizowany kontekst legacy Q dla przyszłego LLM answer synthesizer",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_file_inventory": {
        "description": "Inventory plików starego Q — lista, rozmiary, kategorie",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_entrypoint_inventory": {
        "description": "Wykrywa potencjalne entrypointy starego Q — systemd, shebangi, main",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_capability_scan": {
        "description": "Skanuje pliki w poszukiwaniu funkcji starego Q — qlab, garmin, sync, ride itp.",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_dependency_inventory": {
        "description": "Mapuje zależności starego Q — pip, importy, systemd, external services",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_migration_plan": {
        "description": "Plan migracji starego Q do nowej architektury — fazy, ryzyka, priorytety",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_inventory_answer_context": {
        "description": "Zsanitizowany kontekst inventory/migration legacy Q dla LLM",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_weather_legacy_status": {
        "description": "Read-only status legacy weather/OpenWeatherMap coverage and current weather parity",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_weather_status": {
        "description": "Read-only current weather status via the local weather path",
        "category": "legacy",
        "safe": True,
        "args_schema": {"location": "Marki", "days": 1},
    },
    "qbot_weather_current": {
        "description": "Read-only current weather snapshot and hourly forecast sample",
        "category": "legacy",
        "safe": True,
        "args_schema": {"location": "Marki"},
    },
    "qbot_weather_forecast": {
        "description": "Read-only forecast summary from the local weather path",
        "category": "legacy",
        "safe": True,
        "args_schema": {"location": "Marki", "days": 7},
    },
    "qbot_garage_legacy_status": {
        "description": "Read-only status legacy garage / gate / home automation coverage",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_artifacts_legacy_status": {
        "description": "Read-only status legacy filesystem artifacts vs PostgreSQL artifact bridge",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_artifacts_filesystem_inventory": {
        "description": "Read-only inventory of files in /opt/qbot/artifacts",
        "category": "legacy",
        "safe": True,
        "args_schema": {"prefix": ""},
    },
    "qbot_artifact_import_from_file_preview": {
        "description": "Preview-only artifact import from a filesystem file",
        "category": "legacy",
        "safe": True,
        "args_schema": {"relative_path": "reports/example.json"},
    },
    "qbot_artifact_export_preview": {
        "description": "Preview-only artifact export plan",
        "category": "legacy",
        "safe": True,
        "args_schema": {"artifact_id": 1},
    },
    "qbot_external_integrations_report": {
        "description": "Zbiorczy read-only raport integracji zewnętrznych — weather, garage, artifacts, telegram, MCP, email",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_parity_matrix": {
        "description": "Macierz parity dla wszystkich legacy capabilities — status, evidence, missing tools",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_full_parity_audit": {
        "description": "Pełny read-only audit legacy parity obejmujący wszystkie stare usługi QBot",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_export_status": {
        "description": "Status capability export — pliki, symbole, logi, readiness",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_garmin_status": {
        "description": "Status capability garmin — pliki, symbole, logi, readiness",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garmin_proxy_status": {
        "description": "Read-only status legacy Garmin proxy / fit export surface",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garmin_upload_status": {
        "description": "Read-only status legacy Garmin upload surface",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_hammerhead_import_status": {
        "description": "Read-only status legacy Hammerhead / Karoo import surface",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_qlab_status": {
        "description": "Status capability qlab — server, pliki, symbole, logi",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_sync_status": {
        "description": "Status capability sync — pliki, symbole, logi, readiness",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_capability_status": {
        "description": "Ogólny wrapper dla jednej capability z allowlisty (export|garmin|qlab|sync)",
        "category": "legacy",
        "safe": True,
        "args_schema": {"capability": "export"},
    },
    "qbot_legacy_readonly_wrapper_report": {
        "description": "Zbiorczy raport 4 capability wrappers — readiness, takeover%",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_wrapper_answer_context": {
        "description": "Zsanitizowany kontekst wrapper report dla LLM",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_qlab_smoke_check": {
        "description": "Bezpieczny smoke check QLab server — sprawdza lokalnie endpointy health/status",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_export_dry_run": {
        "description": "Dry-run dla capability export — bez tworzenia eksportu",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_sync_dry_run": {
        "description": "Dry-run dla capability sync — bez synchronizacji i network",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_garmin_dry_run": {
        "description": "Dry-run dla capability garmin — bez logowania do Garmin",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_safe_execution_report": {
        "description": "Zbiorczy raport Phase 2 — smoke check, dry-runs, shadow readiness",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_safe_execution_answer_context": {
        "description": "Zsanitizowany kontekst safe execution report dla LLM",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_shadow_probe": {
        "description": "Shadow probe dla allowlistowanej capability — porównuje legacy z nowym wrapperem",
        "category": "legacy",
        "safe": True,
        "args_schema": {"capability": "qlab"},
    },
    "qbot_legacy_shadow_report": {
        "description": "Raport Phase 3 shadow mode — porównanie 4 capability, cutover readiness",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_shadow_answer_context": {
        "description": "Zsanitizowany kontekst shadow report dla LLM",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_cutover_plan": {
        "description": "Plan przełączenia cutover — PLAN_ONLY, bez wykonywania",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_cutover_readiness_gate": {
        "description": "Finalna bramka gotowości do cutover — PASS/PASS_WITH_WARNINGS/BLOCKED",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_manual_cutover_plan": {
        "description": "Dokładny plan manualnego przełączenia — PLAN_ONLY, komendy tylko do przeglądu",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_cutover_answer_context": {
        "description": "Zsanitizowany kontekst cutover readiness gate + plan dla LLM",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_takeover_status": {
        "description": "Syntetyczny status przejęcia starego Q — fazy, procent, gotowość",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_cutover_status": {
        "description": "Status cutover — czy q-bot.service zatrzymany, czy API działa",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_legacy_rollback_plan": {
        "description": "Plan rollbacku legacy Q — PLAN_ONLY, komendy do ręcznego wykonania",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_llm_provider_status": {
        "description": "Status providera LLM — czy dostępny klucz API (bez ujawniania)",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_tool_policy_list": {
        "description": "Lista wszystkich tooli z metadanymi bezpieczeństwa — safety_class, requires_approval",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_llm_plan_query": {
        "description": "Planuje narzędzia dla zapytania — LLM proponuje, Qbot waliduje (fallback: rule-based)",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"query": "sprawdź stan qbot", "mode": "preview"},
    },
    "qbot_policy_validate_plan": {
        "description": "Waliduje proposed_plan przez policy engine — zwraca approved/blocked/requires_approval",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"plan": {}},
    },
    "qbot_execute_validated_plan": {
        "description": "Wykonuje zatwierdzony plan — tylko READ_ONLY auto-execute, CONTROLLED_ACTION wymaga approval",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"plan_id": 1, "execute": False, "approval": False},
    },
    "qbot_llm_run_query": {
        "description": "Pełen pipeline: plan → validate → execute → summarize (LLM proposes, Qbot disposes)",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"query": "sprawdź stan qbot", "execute": False, "style": "concise"},
    },
    "qbot_artifact_create": {
        "description": "Tworzy artifact w PostgreSQL — WRITE_SAFE, max 100 KB, blokuje sekrety",
        "category": "artifact",
        "safe": True,
        "args_schema": {"artifact_type": "report", "title": "...", "content": "..."},
    },
    "qbot_artifact_list": {
        "description": "Lista ostatnich artifactów — READ_ONLY, limit 1-100",
        "category": "artifact",
        "safe": True,
        "args_schema": {"limit": 20},
    },
    "qbot_artifact_get": {
        "description": "Pobiera artifact po ID — READ_ONLY, pełna treść do 100 KB",
        "category": "artifact",
        "safe": True,
        "args_schema": {"id": 1},
    },
    "qbot_workspace_write_file_preview": {
        "description": "Podgląd zapisu pliku do workspace — PREVIEW_ONLY v1, waliduje ścieżkę i sekrety",
        "category": "artifact",
        "safe": True,
        "args_schema": {"relative_path": "reports/test.md", "content": "# test"},
    },
    "qbot_external_llm_status": {
        "description": "Status trybu External LLM — ChatGPT Plus zewnętrzny, API disabled",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_external_llm_policy": {
        "description": "Polityka modeli — ChatGPT external primary, DeepSeek dev-only",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_external_context_bundle": {
        "description": "Przygotowuje zsanitizowany kontekst dla zewnętrznej sesji ChatGPT Plus",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"topic": "operational_status", "max_chars": 12000},
    },
    "qbot_chatgpt_prompt_pack": {
        "description": "Generuje gotowy prompt do wklejenia w ChatGPT Plus — rola, kontekst, ograniczenia",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {"topic": "operational_status", "task": "...", "style": "concise"},
    },
    "qbot_chatgpt_decision_record_create": {
        "description": "Zapisuje decyzję z ChatGPT jako decision_record w PostgreSQL",
        "category": "artifact",
        "safe": True,
        "args_schema": {"title": "...", "decision": "...", "rationale": "...", "tags": []},
    },
    "qbot_external_llm_workflow_guide": {
        "description": "Instrukcja workflow: context bundle → prompt pack → ChatGPT → decision record",
        "category": "llm_boundary",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_legacy_audit": {
        "description": "audyT starej konfiguracji Telegram/ngrok — read-only, bez tokenów",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_config_status": {
        "description": "Sprawdza obecność zmiennych TELEGRAM_* w .env bez ujawniania wartości",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_public_endpoint_status": {
        "description": "Sprawdza publiczny endpoint — QBOT_PUBLIC_BASE_URL, HTTPS, reverse proxy",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_status": {
        "description": "Zbiorczy status Telegram bota po cutover — API, DB, webhook, legacy takeover",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_webhook_plan": {
        "description": "Plan webhooka Telegram — expected URL, manual commands, verification steps",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_set_webhook": {
        "description": "Ustawia Telegram webhook — preview lub execute, wymaga https://",
        "category": "telegram",
        "safe": True,
        "args_schema": {"execute": False},
    },
    "qbot_telegram_delete_webhook": {
        "description": "Usuwa Telegram webhook — preview by default, rollback option",
        "category": "telegram",
        "safe": True,
        "args_schema": {"execute": False},
    },
    "qbot_telegram_send_test": {
        "description": "Wysyła testową wiadomość do allowed chat_id (max 1000 znaków)",
        "category": "telegram",
        "safe": True,
        "args_schema": {"chat_id": None, "text": "Qbot Telegram test"},
    },
    "qbot_telegram_command_help": {
        "description": "Lista dostępnych komend Telegram bota",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_answer_context": {
        "description": "Bezpieczny zsanitizowany kontekst Telegram dla LLM — bez sekretów",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_runtime_self_check": {
        "description": "Test runtime Telegram — send test + synthetic dispatch",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_conversation_self_check": {
        "description": "Test konwersacyjny — sprawdza czy plain text idzie przez /ask i unknown_intent nie jest user-facing",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_agent_chat": {
        "description": "Centralny agent Qbot dla Telegram — pełny dostęp do tool registry i policy engine",
        "category": "telegram",
        "safe": True,
        "args_schema": {"message": "to jaka jest moja forma w XERT?", "execute": True},
    },
    "qbot_telegram_agent_chat_self_check": {
        "description": "Test agent chat — sprawdza czy agent widzi pełne registry i używa tooli",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_telegram_llm_chat": {
        "description": "LLM chat dla Telegram — krótka odpowiedź na dowolne pytanie użytkownika",
        "category": "telegram",
        "safe": True,
        "args_schema": {"message": "czy qbot działa?", "style": "short"},
    },
    "qbot_telegram_llm_chat_self_check": {
        "description": "Test LLM chat — sprawdza czy plain text idzie do LLM i pytania są obsługiwane",
        "category": "telegram",
        "safe": True,
        "args_schema": {},
    },
    "qbot_rwgps_config_status": {
        "description": "Sprawdza konfigurację RWGPS bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_rwgps_legacy_status": {
        "description": "Kompleksowy status legacy RWGPS — kod, konfiguracja, artefakty",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_rwgps_dry_run": {
        "description": "Bezpieczny dry-run RWGPS — tylko read-only, brak uploadu/syncu",
        "category": "legacy",
        "safe": True,
        "args_schema": {"operation": "list_routes"},
    },
    "qbot_rwgps_restore_plan": {
        "description": "Plan przywrócenia RWGPS z brakującymi krokami",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_hammerhead_config_status": {
        "description": "Sprawdza konfigurację Hammerhead — tokeny, JWT, tokenstore",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_hammerhead_import_inventory": {
        "description": "Listuje pliki FIT z Hammerhead originals w outgoing",
        "category": "legacy",
        "safe": True,
        "args_schema": {"limit": 20},
    },
    "qbot_hammerhead_import_dry_run": {
        "description": "Bezpieczny dry-run importu Hammerhead — bez pobierania/syncu",
        "category": "legacy",
        "safe": True,
        "args_schema": {"source": "latest"},
    },
    "qbot_hammerhead_restore_plan": {
        "description": "Plan przywrócenia Hammerhead FIT importu",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_csv_export_inventory": {
        "description": "Listuje pliki CSV w outgoing — read-only",
        "category": "legacy",
        "safe": True,
        "args_schema": {"limit": 20},
    },
    "qbot_csv_export_latest_get": {
        "description": "Odczyt ostatniego CSV — read-only, max limit_rows 200",
        "category": "legacy",
        "safe": True,
        "args_schema": {"source": "garmin_proxy_latest", "limit_rows": 20},
    },
    "qbot_csv_export_create_preview": {
        "description": "Podgląd co zostałoby wygenerowane do CSV — bez zapisu",
        "category": "legacy",
        "safe": True,
        "args_schema": {"source_report": "latest", "output_name": "preview"},
    },
    "qbot_csv_export_create_execute": {
        "description": "Wykonaj eksport CSV do outgoing/exports/ — dry_run domyślnie true",
        "category": "legacy",
        "safe": True,
        "args_schema": {"source_report": "latest", "output_name": "qbot_export_latest.csv", "dry_run": True},
    },
    "qbot_csv_export_status": {
        "description": "Zbiorczy status CSV export — inventory + latest + preview",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_xert_config_status": {
        "description": "Sprawdza konfigurację Xert bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_xert_readiness_status": {
        "description": "Pobiera dane treningowe z Xert — FTP, forma, W'",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_xert_restore_plan": {
        "description": "Plan przywrócenia integracji Xert",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_intervals_config_status": {
        "description": "Sprawdza konfigurację Intervals.icu bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_intervals_wellness_status": {
        "description": "Pobiera dane wellness z Intervals.icu",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_intervals_restore_plan": {
        "description": "Plan przywrócenia integracji Intervals.icu",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garmin_config_status": {
        "description": "Sprawdza konfigurację Garmin bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garmin_upload_dry_run": {
        "description": "Bezpieczny dry-run uploadu do Garmin — bez wysyłania danych",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garmin_restore_plan": {
        "description": "Plan przywrócenia integracji Garmin",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_cronometer_config_status": {
        "description": "Sprawdza konfigurację Cronometer bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_cronometer_legacy_status": {
        "description": "Kompleksowy status legacy Cronometer",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_cronometer_restore_plan": {
        "description": "Plan przywrócenia integracji Cronometer",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_weather_config_status": {
        "description": "Sprawdza konfigurację pogody bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_resolve_user_location": {
        "description": "Ustala lokalizację użytkownika z tekstu, env, lub profilu",
        "category": "legacy",
        "safe": True,
        "args_schema": {"text": "sprawdź pogodę dla Marek"},
    },
    "qbot_weather_current": {
        "description": "Aktualna pogoda — OpenWeatherMap primary, Open-Meteo fallback",
        "category": "legacy",
        "safe": True,
        "args_schema": {"location": "Marki,PL", "units": "metric", "lang": "pl"},
    },
    "qbot_weather_forecast": {
        "description": "Prognoza pogody — godziny, opady, wiatr",
        "category": "legacy",
        "safe": True,
        "args_schema": {"location": "Marki,PL", "period": "tomorrow_morning", "hours": 12},
    },
    "qbot_public_web_fallback_self_check": {
        "description": "Sprawdza czy public web fallback działa dla pogody i geokodowania",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_public_web_status": {
        "description": "Status public web fallback — czy można używać publicznych źródeł",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_public_web_fetch": {
        "description": "Public web fetch — pogoda, mapy, docs, news z jawnymi źródłami",
        "category": "legacy",
        "safe": True,
        "args_schema": {"query": "pogoda Marki", "topic": "weather"},
    },
    "qbot_openmaps_config_status": {
        "description": "Sprawdza konfigurację OpenMaps bez wypisywania sekretów",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_openmaps_legacy_status": {
        "description": "Kompleksowy status legacy OpenMaps",
        "category": "legacy",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garage_legacy_file_audit": {
        "description": "Audyt plików legacy w katalogu Garage",
        "category": "garage",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garage_import_preview": {
        "description": "Podgląd importu plików do Garage — bez zapisu",
        "category": "garage",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garage_import_execute": {
        "description": "Wykonaj import plików do Garage — dry_run domyślnie True",
        "category": "garage",
        "safe": True,
        "args_schema": {"dry_run": True},
    },
    "qbot_garage_raw_status": {
        "description": "Status bazy Garage raw — tabele, liczniki",
        "category": "garage",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garage_raw_list": {
        "description": "Lista ostatnich wpisów w Garage raw",
        "category": "garage",
        "safe": True,
        "args_schema": {"limit": 20},
    },
    "qbot_garage_raw_get": {
        "description": "Pobiera wpis Garage raw po ID",
        "category": "garage",
        "safe": True,
        "args_schema": {},
    },
    "qbot_garage_raw_search": {
        "description": "Wyszukuje wpisy w Garage raw po frazie",
        "category": "garage",
        "safe": True,
        "args_schema": {},
    },
    "qbot_daily_report_status": {
        "description": "Status raportu dziennego — konfiguracja, dane",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_daily_report_preview": {
        "description": "Podgląd raportu dziennego przed wysyłką",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_daily_report_send": {
        "description": "Wyślij raport dzienny przez Telegram",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_ride_report_status": {
        "description": "Status raportów przejazdów — konfiguracja, dane",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_ride_report_latest": {
        "description": "Pobiera najnowszy raport przejazdu",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_ride_report_preview": {
        "description": "Podgląd raportu przejazdu przed wysyłką",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_ride_report_send": {
        "description": "Wyślij raport przejazdu przez Telegram",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_reports_schedule_status": {
        "description": "Status harmonogramu raportów — timery, harmonogram",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
    "qbot_reports_restore_plan": {
        "description": "Plan przywrócenia systemu raportów",
        "category": "reports",
        "safe": True,
        "args_schema": {},
    },
}

TOOLS: dict[str, Any] = {
    "qbot_status": _tool_qbot_status,
    "qbot_services_status": _tool_qbot_services_status,
    "qbot_recent_tool_calls": _tool_qbot_recent_tool_calls,
    "qbot_git_status": _tool_qbot_git_status,
    "qbot_api_tools_list": _tool_qbot_api_tools_list,
    "qbot_db_overview": _tool_qbot_db_overview,
    "qbot_system_overview": _tool_qbot_system_overview,
    "qbot_api_self_check": _tool_qbot_api_self_check,
    "qbot_ride_readiness_status": _tool_qbot_ride_readiness_status,
    "qbot_project_tree": _tool_qbot_project_tree,
    "qbot_project_files": _tool_qbot_project_files,
    "qbot_project_recent_commits": _tool_qbot_project_recent_commits,
    "qbot_project_diff_summary": _tool_qbot_project_diff_summary,
    "qbot_project_guard_check": _tool_qbot_project_guard_check,
    "qbot_query": _tool_qbot_query,
    "qbot_error_summary": _tool_qbot_error_summary,
    "qbot_tool_usage_summary": _tool_qbot_tool_usage_summary,
    "qbot_readiness_report": _tool_qbot_readiness_report,
    "qbot_operator_snapshot": _tool_qbot_operator_snapshot,
    "qbot_operator_runbook": _tool_qbot_operator_runbook,
    "qbot_service_logs": _tool_qbot_service_logs,
    "qbot_logs_overview": _tool_qbot_logs_overview,
    "qbot_backup_status": _tool_qbot_backup_status,
    "qbot_backup_plan": _tool_qbot_backup_plan,
    "qbot_create_backup_script_preview": _tool_qbot_create_backup_script_preview,
    "qbot_test_error_classification": _tool_qbot_test_error_classification,
    "qbot_maintenance_report": _tool_qbot_maintenance_report,
    "qbot_backup_timer_status": _tool_qbot_backup_timer_status,
    "qbot_restore_drill_plan": _tool_qbot_restore_drill_plan,
    "qbot_restore_drill_status": _tool_qbot_restore_drill_status,
    "qbot_operator_quick_reference": _tool_qbot_operator_quick_reference,
    "qbot_answer_context": _tool_qbot_answer_context,
    "qbot_llm_boundary_policy": _tool_qbot_llm_boundary_policy,
    "qbot_operator_final_smoke_test": _tool_qbot_operator_final_smoke_test,
    "qbot_mcp_status": _tool_qbot_mcp_status,
    "qbot_mcp_tools_list": _tool_qbot_mcp_tools_list,
    "qbot_mcp_call_preview": _tool_qbot_mcp_call_preview,
    "qbot_legacy_status": _tool_qbot_legacy_status,
    "qbot_legacy_logs": _tool_qbot_legacy_logs,
    "qbot_legacy_error_summary": _tool_qbot_legacy_error_summary,
    "qbot_legacy_health_report": _tool_qbot_legacy_health_report,
    "qbot_legacy_answer_context": _tool_qbot_legacy_answer_context,
    "qbot_legacy_file_inventory": _tool_qbot_legacy_file_inventory,
    "qbot_legacy_entrypoint_inventory": _tool_qbot_legacy_entrypoint_inventory,
    "qbot_legacy_capability_scan": _tool_qbot_legacy_capability_scan,
    "qbot_legacy_dependency_inventory": _tool_qbot_legacy_dependency_inventory,
    "qbot_legacy_migration_plan": _tool_qbot_legacy_migration_plan,
    "qbot_legacy_inventory_answer_context": _tool_qbot_legacy_inventory_answer_context,
    "qbot_weather_legacy_status": _tool_qbot_weather_legacy_status,
    "qbot_weather_status": _tool_qbot_weather_status,
    "qbot_weather_current": _tool_qbot_weather_current,
    "qbot_weather_forecast": _tool_qbot_weather_forecast,
    "qbot_resolve_user_location": _tool_qbot_resolve_user_location,
    "qbot_public_web_fallback_self_check": _tool_qbot_public_web_fallback_self_check,
    "qbot_public_web_status": _tool_qbot_public_web_status,
    "qbot_public_web_fetch": _tool_qbot_public_web_fetch,
    "qbot_garage_legacy_status": _tool_qbot_garage_legacy_status,
    "qbot_artifacts_legacy_status": _tool_qbot_artifacts_legacy_status,
    "qbot_artifacts_filesystem_inventory": _tool_qbot_artifacts_filesystem_inventory,
    "qbot_artifact_import_from_file_preview": _tool_qbot_artifact_import_from_file_preview,
    "qbot_artifact_export_preview": _tool_qbot_artifact_export_preview,
    "qbot_external_integrations_report": _tool_qbot_external_integrations_report,
    "qbot_legacy_parity_matrix": _tool_qbot_legacy_parity_matrix,
    "qbot_legacy_full_parity_audit": _tool_qbot_legacy_full_parity_audit,
    "qbot_legacy_export_status": _tool_qbot_legacy_export_status,
    "qbot_legacy_garmin_status": _tool_qbot_legacy_garmin_status,
    "qbot_garmin_proxy_status": _tool_qbot_garmin_proxy_status,
    "qbot_garmin_upload_status": _tool_qbot_garmin_upload_status,
    "qbot_hammerhead_import_status": _tool_qbot_hammerhead_import_status_enhanced,
    "qbot_legacy_qlab_status": _tool_qbot_legacy_qlab_status,
    "qbot_legacy_sync_status": _tool_qbot_legacy_sync_status,
    "qbot_legacy_capability_status": _tool_qbot_legacy_capability_status,
    "qbot_legacy_readonly_wrapper_report": _tool_qbot_legacy_readonly_wrapper_report,
    "qbot_legacy_wrapper_answer_context": _tool_qbot_legacy_wrapper_answer_context,
    "qbot_legacy_qlab_smoke_check": _tool_qbot_legacy_qlab_smoke_check,
    "qbot_legacy_export_dry_run": _tool_qbot_legacy_export_dry_run,
    "qbot_legacy_sync_dry_run": _tool_qbot_legacy_sync_dry_run,
    "qbot_legacy_garmin_dry_run": _tool_qbot_legacy_garmin_dry_run,
    "qbot_legacy_safe_execution_report": _tool_qbot_legacy_safe_execution_report,
    "qbot_legacy_safe_execution_answer_context": _tool_qbot_legacy_safe_execution_answer_context,
    "qbot_legacy_shadow_probe": _tool_qbot_legacy_shadow_probe,
    "qbot_legacy_shadow_report": _tool_qbot_legacy_shadow_report,
    "qbot_legacy_shadow_answer_context": _tool_qbot_legacy_shadow_answer_context,
    "qbot_legacy_cutover_plan": _tool_qbot_legacy_cutover_plan,
    "qbot_legacy_cutover_readiness_gate": _tool_qbot_legacy_cutover_readiness_gate,
    "qbot_legacy_manual_cutover_plan": _tool_qbot_legacy_manual_cutover_plan,
    "qbot_legacy_cutover_answer_context": _tool_qbot_legacy_cutover_answer_context,
    "qbot_legacy_takeover_status": _tool_qbot_legacy_takeover_status,
    "qbot_legacy_cutover_status": _tool_qbot_legacy_cutover_status,
    "qbot_legacy_rollback_plan": _tool_qbot_legacy_rollback_plan,
    "qbot_llm_provider_status": _tool_qbot_llm_provider_status,
    "qbot_tool_policy_list": _tool_qbot_tool_policy_list,
    "qbot_llm_plan_query": _tool_qbot_llm_plan_query,
    "qbot_policy_validate_plan": _tool_qbot_policy_validate_plan,
    "qbot_execute_validated_plan": _tool_qbot_execute_validated_plan,
    "qbot_llm_run_query": _tool_qbot_llm_run_query,
    "qbot_artifact_create": _tool_qbot_artifact_create,
    "qbot_artifact_list": _tool_qbot_artifact_list,
    "qbot_artifact_get": _tool_qbot_artifact_get,
    "qbot_workspace_write_file_preview": _tool_qbot_workspace_write_file_preview,
    "qbot_external_llm_status": _tool_qbot_external_llm_status,
    "qbot_external_llm_policy": _tool_qbot_external_llm_policy,
    "qbot_external_context_bundle": _tool_qbot_external_context_bundle,
    "qbot_chatgpt_prompt_pack": _tool_qbot_chatgpt_prompt_pack,
    "qbot_chatgpt_decision_record_create": _tool_qbot_chatgpt_decision_record_create,
    "qbot_external_llm_workflow_guide": _tool_qbot_external_llm_workflow_guide,
    "qbot_telegram_legacy_audit": _tool_qbot_telegram_legacy_audit,
    "qbot_telegram_config_status": _tool_qbot_telegram_config_status,
    "qbot_public_endpoint_status": _tool_qbot_public_endpoint_status,
    "qbot_telegram_status": _tool_qbot_telegram_status,
    "qbot_telegram_webhook_plan": _tool_qbot_telegram_webhook_plan,
    "qbot_telegram_set_webhook": _tool_qbot_telegram_set_webhook,
    "qbot_telegram_delete_webhook": _tool_qbot_telegram_delete_webhook,
    "qbot_telegram_send_test": _tool_qbot_telegram_send_test,
    "qbot_telegram_command_help": _tool_qbot_telegram_command_help,
    "qbot_telegram_answer_context": _tool_qbot_telegram_answer_context,
    "qbot_telegram_runtime_self_check": _tool_qbot_telegram_runtime_self_check,
    "qbot_telegram_conversation_self_check": _tool_qbot_telegram_conversation_self_check,
    "qbot_telegram_agent_chat": _tool_qbot_telegram_agent_chat,
    "qbot_telegram_agent_chat_self_check": _tool_qbot_telegram_agent_chat_self_check,
    "qbot_telegram_llm_chat": _tool_qbot_telegram_llm_chat,
    "qbot_telegram_llm_chat_self_check": _tool_qbot_telegram_llm_chat_self_check,
    "qbot_rwgps_config_status": _tool_qbot_rwgps_config_status,
    "qbot_rwgps_legacy_status": _tool_qbot_rwgps_legacy_status,
    "qbot_rwgps_dry_run": _tool_qbot_rwgps_dry_run,
    "qbot_rwgps_restore_plan": _tool_qbot_rwgps_restore_plan,
    "qbot_hammerhead_config_status": _tool_qbot_hammerhead_config_status,
    "qbot_hammerhead_import_inventory": _tool_qbot_hammerhead_import_inventory,
    "qbot_hammerhead_import_dry_run": _tool_qbot_hammerhead_import_dry_run,
    "qbot_hammerhead_restore_plan": _tool_qbot_hammerhead_restore_plan,
    "qbot_csv_export_inventory": _tool_qbot_csv_export_inventory,
    "qbot_csv_export_latest_get": _tool_qbot_csv_export_latest_get,
    "qbot_csv_export_create_preview": _tool_qbot_csv_export_create_preview,
    "qbot_csv_export_create_execute": _tool_qbot_csv_export_create_execute,
    "qbot_csv_export_status": _tool_qbot_csv_export_status,
    "qbot_xert_config_status": _tool_qbot_xert_config_status,
    "qbot_xert_readiness_status": _tool_qbot_xert_readiness_status,
    "qbot_xert_restore_plan": _tool_qbot_xert_restore_plan,
    "qbot_intervals_config_status": _tool_qbot_intervals_config_status,
    "qbot_intervals_wellness_status": _tool_qbot_intervals_wellness_status,
    "qbot_intervals_restore_plan": _tool_qbot_intervals_restore_plan,
    "qbot_garmin_config_status": _tool_qbot_garmin_config_status,
    "qbot_garmin_upload_dry_run": _tool_qbot_garmin_upload_dry_run,
    "qbot_garmin_restore_plan": _tool_qbot_garmin_restore_plan,
    "qbot_cronometer_config_status": _tool_qbot_cronometer_config_status,
    "qbot_cronometer_legacy_status": _tool_qbot_cronometer_legacy_status,
    "qbot_cronometer_restore_plan": _tool_qbot_cronometer_restore_plan,
    "qbot_weather_config_status": _tool_qbot_weather_config_status,
    "qbot_openmaps_config_status": _tool_qbot_openmaps_config_status,
    "qbot_openmaps_legacy_status": _tool_qbot_openmaps_legacy_status,
    "qbot_garage_legacy_file_audit": _tool_qbot_garage_legacy_file_audit,
    "qbot_garage_import_preview": _tool_qbot_garage_import_preview,
    "qbot_garage_import_execute": _tool_qbot_garage_import_execute,
    "qbot_garage_raw_status": _tool_qbot_garage_raw_status,
    "qbot_garage_raw_list": _tool_qbot_garage_raw_list,
    "qbot_garage_raw_get": _tool_qbot_garage_raw_get,
    "qbot_garage_raw_search": _tool_qbot_garage_raw_search,
    "qbot_daily_report_status": _tool_qbot_daily_report_status,
    "qbot_daily_report_preview": _tool_qbot_daily_report_preview,
    "qbot_daily_report_send": _tool_qbot_daily_report_send,
    "qbot_ride_report_status": _tool_qbot_ride_report_status,
    "qbot_ride_report_latest": _tool_qbot_ride_report_latest,
    "qbot_ride_report_preview": _tool_qbot_ride_report_preview,
    "qbot_ride_report_send": _tool_qbot_ride_report_send,
    "qbot_reports_schedule_status": _tool_qbot_reports_schedule_status,
    "qbot_reports_restore_plan": _tool_qbot_reports_restore_plan,
}
