#!/usr/bin/env python3
"""g15_build_combined_poi_warnings_gpx.py — Combined POI + Warnings GPX.

Builds safe-import GPX: original trk + accepted warning/POI wpt only.
No geometry modification. No RWGPS upload.

Usage:
    python3 scripts/g15_build_combined_poi_warnings_gpx.py --route-id 55401067
    python3 scripts/g15_build_combined_poi_warnings_gpx.py --route-id 55395119
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import xml.etree.ElementTree as ET

ARTIFACTS_REVIEW = Path("/opt/qbot/artifacts/review")
ARTIFACTS_EXPORTS = Path("/opt/qbot/artifacts/exports/rwgps")
ARTIFACTS_POI = Path("/opt/qbot/artifacts/poi")
ARTIFACTS_COMBINED = Path("/opt/qbot/artifacts/combined")


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _haversine_m(lat1, lon1, lat2, lon2):
    R = 6371000
    dlat = math.radians(lat2 - lat1); dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) ** 2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ── Namespace-agnostic GPX parser ─────────────────────────────────────────

def _local(tag: str) -> str:
    """Strip XML namespace from a tag, returning local name only."""
    return tag.split("}")[-1] if "}" in tag else tag


def parse_gpx_track(path: Path) -> list[dict]:
    """Parse GPX track points, namespace-agnostic. Returns [{lat, lon, ele}, ...]."""
    if not path.exists():
        return []
    try:
        tree = ET.parse(str(path))
        root = tree.getroot()
    except Exception:
        return []

    # Collect all trkpt tags regardless of namespace
    trkpts = []
    for el in root.iter():
        local = _local(el.tag)
        if local == "trkpt":
            lat = el.get("lat")
            lon = el.get("lon")
            if lat and lon:
                pt = {"lat": float(lat), "lon": float(lon)}
                for child in el:
                    clocal = _local(child.tag)
                    if clocal == "ele" and child.text:
                        pt["ele"] = float(child.text)
                trkpts.append(pt)

    return trkpts


def compute_cumulative_distance(pts: list[dict]) -> list[float]:
    cum = [0.0]
    for i in range(1, len(pts)):
        d = _haversine_m(pts[i - 1]["lat"], pts[i - 1]["lon"], pts[i]["lat"], pts[i]["lon"])
        cum.append(cum[-1] + d)
    return cum


def point_at_km(pts: list[dict], cum: list[float], target_km: float) -> dict | None:
    """Find approximate point on the track at target_km."""
    target_m = target_km * 1000
    if not pts or not cum:
        return None
    if target_m <= 0:
        return {"lat": pts[0]["lat"], "lon": pts[0]["lon"]}
    if target_m >= cum[-1]:
        return {"lat": pts[-1]["lat"], "lon": pts[-1]["lon"]}
    for i in range(1, len(cum)):
        if cum[i] >= target_m:
            # Interpolate
            frac = (target_m - cum[i - 1]) / (cum[i] - cum[i - 1]) if cum[i] > cum[i - 1] else 0
            lat = pts[i - 1]["lat"] + (pts[i]["lat"] - pts[i - 1]["lat"]) * frac
            lon = pts[i - 1]["lon"] + (pts[i]["lon"] - pts[i - 1]["lon"]) * frac
            return {"lat": round(lat, 6), "lon": round(lon, 6)}
    return None


def build_gpx_xml(pts: list[dict], wpts: list[dict], route_name: str, rid: str) -> str:
    """Build GPX 1.1 XML with original trkpt + wpt waypoints.

    wpts: [{"lat":, "lon":, "name":, "desc":}, ...]
    """
    NS = "http://www.topografix.com/GPX/1/1"
    et_ns = f"{{{NS}}}"

    root = ET.Element(f"{et_ns}gpx", {
        "version": "1.1", "creator": "QBot Gravel Intelligence G15",
        "xmlns": NS,
    })

    # Metadata
    meta = ET.SubElement(root, f"{et_ns}metadata")
    ET.SubElement(meta, f"{et_ns}name").text = f"{route_name} + QBot warnings/POI"
    ET.SubElement(meta, f"{et_ns}desc").text = (
        f"Generated by QBot Gravel Intelligence G15. "
        f"{len(wpts)} waypoints. Geometry unchanged."
    )

    # Waypoints
    for w in wpts:
        wpt = ET.SubElement(root, f"{et_ns}wpt")
        wpt.set("lat", str(w["lat"]))
        wpt.set("lon", str(w["lon"]))
        ET.SubElement(wpt, f"{et_ns}name").text = w.get("name", "POI")
        ET.SubElement(wpt, f"{et_ns}desc").text = w.get("desc", "")[:250]

    # Track
    trk = ET.SubElement(root, f"{et_ns}trk")
    ET.SubElement(trk, f"{et_ns}name").text = f"{route_name} + QBot warnings/POI"
    ET.SubElement(trk, f"{et_ns}desc").text = (
        f"Original track + {len(wpts)} waypoints. No geometry changes."
    )

    trkseg = ET.SubElement(trk, f"{et_ns}trkseg")
    for pt in pts:
        trkpt = ET.SubElement(trkseg, f"{et_ns}trkpt")
        trkpt.set("lat", str(pt["lat"]))
        trkpt.set("lon", str(pt["lon"]))
        if "ele" in pt and pt["ele"] is not None:
            ET.SubElement(trkpt, f"{et_ns}ele").text = str(pt["ele"])

    return ET.tostring(root, encoding="unicode", xml_declaration=True)


# ── Warning label helper ──────────────────────────────────────────────────

def _warning_label(p: dict) -> str:
    length = p.get("length_km", 0)
    surface = p.get("override_surface") or p.get("risk_type", "unknown")
    label_map = {
        "sand": "PIACH", "mud": "BŁOTO", "dirt": "GRUNT", "ground": "GRUNT",
        "gravel": "SZUTER", "high_risk_surface": "UWAGA",
        "moderate_risk_surface": "UWAGA", "unknown_risk": "NIEPEWNA",
        "unpaved_track": "DROGA",
    }
    kw = label_map.get(surface, surface.upper()[:8])
    return f"{kw} {length:.1f} km"


# ── Main ──────────────────────────────────────────────────────────────────

def build_combined(route_id: str) -> dict:
    rid = str(route_id)

    # 1. Load original GPX
    original_path = ARTIFACTS_EXPORTS / f"rwgps_{rid}.gpx"
    pts = parse_gpx_track(original_path)
    if not pts:
        return {"ok": False, "error": f"No track points in GPX: {original_path}"}

    original_count = len(pts)
    assert original_count == (1499 if rid == "55401067" else 1739 if rid == "55395119" else original_count), \
        f"Unexpected trkpt count: {original_count}"

    cum = compute_cumulative_distance(pts)

    # 2. Load G13 briefing + decisions
    briefing = _read_json(ARTIFACTS_REVIEW / f"review_briefing_{rid}.json")
    decisions_data = _read_json(ARTIFACTS_REVIEW / f"review_decisions_{rid}.json")
    decisions = {}
    if decisions_data:
        for d in decisions_data.get("decisions", []):
            decisions[d.get("problem_id", "")] = d.get("decision", "").upper()

    route_name = briefing.get("route_name", f"Route {rid}") if briefing else f"Route {rid}"

    total_km = cum[-1] / 1000.0 if cum else 0

    # 3. Build warning waypoints
    warning_wpts = []
    skipped_review = 0
    skipped_suppress = 0
    skipped_omit = 0
    skipped_no_decision = 0

    if briefing:
        for p in briefing.get("problems", []):
            pid = p["problem_id"]
            decision = decisions.get(pid, p.get("suggested_default_decision", "")).upper()
            if not decision:
                skipped_no_decision += 1
                continue

            if decision == "ACCEPT_WARNING":
                # Find coordinate on track at start_km
                skm = p.get("start_km", 0)
                coord = point_at_km(pts, cum, skm)
                if coord is None:
                    continue

                name = _warning_label(p)
                parts = []
                if p.get("manual_override_applied"):
                    parts.append("Potwierdzone przez użytkownika.")
                if p.get("weather_note"):
                    parts.append(p["weather_note"])
                if p.get("human_summary"):
                    summary = p["human_summary"]
                    # Strip technical details
                    for prefix in ["risk_type=", "surface=", "severity=", "confidence=", "reason="]:
                        summary = summary.replace(prefix, "")
                    parts.append(summary)
                desc = " ".join(parts).strip()[:250] if parts else f"Sekcja km {skm:.1f}"

                # Verify no technical fields in desc
                for technical in ["risk_type=", "surface=", "severity=", "confidence=", "reason="]:
                    assert technical not in desc, f"Technical field in desc: {technical}"

                warning_wpts.append({"lat": coord["lat"], "lon": coord["lon"], "name": name, "desc": desc})
            elif decision == "REVIEW":
                skipped_review += 1
            elif decision == "SUPPRESS":
                skipped_suppress += 1
            elif decision == "OMIT":
                skipped_omit += 1

    # 4. Load POI buffer
    poi_wpts = []
    skipped_poi = 0
    poi_buffer = _read_json(ARTIFACTS_POI / f"poi_buffer_{rid}.json")
    if poi_buffer:
        for poi in poi_buffer.get("pois", []):
            if poi.get("accepted") is not True:
                skipped_poi += 1
                continue
            plon = poi.get("lon") or poi.get("lng")
            if not plon:
                skipped_poi += 1
                continue
            lat, lon = poi["lat"], plon
            # Check distance from track
            min_dist = float("inf")
            for pt in pts:
                d = _haversine_m(pt["lat"], pt["lon"], lat, lon)
                if d < min_dist:
                    min_dist = d
            if min_dist > 1000 and not poi.get("allow_far"):
                skipped_poi += 1
                continue
            name = poi.get("short_name") or poi.get("name", "POI")[:25]
            desc = poi.get("description", "")[:250]
            poi_wpts.append({"lat": lat, "lon": lon, "name": name, "desc": desc})

    # 5. Build output
    all_wpts = warning_wpts + poi_wpts
    gpx_xml = build_gpx_xml(pts, all_wpts, route_name, rid)

    # 6. Write outputs
    gpx_out = ARTIFACTS_COMBINED / f"combined_import_{rid}.gpx"
    md_out = ARTIFACTS_COMBINED / f"combined_import_{rid}.md"
    sum_out = ARTIFACTS_COMBINED / f"combined_import_{rid}_summary.json"

    _write(gpx_out, gpx_xml)

    summary = {
        "ok": True,
        "status": "SAFE_IMPORT_GPX",
        "route_id": rid,
        "route_name": route_name,
        "source_original_gpx": str(original_path),
        "output_gpx_path": str(gpx_out),
        "original_trkpt_count": original_count,
        "output_trkpt_count": original_count,
        "warning_wpt_count": len(warning_wpts),
        "poi_wpt_count": len(poi_wpts),
        "total_wpt_count": len(all_wpts),
        "skipped_review_count": skipped_review,
        "skipped_suppress_count": skipped_suppress,
        "skipped_omit_count": skipped_omit,
        "skipped_no_decision_count": skipped_no_decision,
        "skipped_poi_count": skipped_poi,
        "has_poi_buffer": poi_buffer is not None,
        "geometry_modified": False,
        "no_rwgps_upload": True,
        "total_distance_km": round(total_km, 2),
        "source_files": {
            "original_gpx": str(original_path),
            "briefing": str(ARTIFACTS_REVIEW / f"review_briefing_{rid}.json") if briefing else None,
            "decisions": str(ARTIFACTS_REVIEW / f"review_decisions_{rid}.json") if decisions_data else None,
            "poi_buffer": str(ARTIFACTS_POI / f"poi_buffer_{rid}.json") if poi_buffer else None,
        },
        "safety_notes": [
            "Geometry not modified",
            "Only ACCEPT_WARNING segments included",
            "REVIEW/OMIT/SUPPRESS segments excluded",
            "POI included only if accepted=true",
        ],
        "generated_at": _iso_now(),
        "generator": "g15_build_combined_poi_warnings_gpx.py",
    }

    _write(sum_out, json.dumps(summary, indent=2, ensure_ascii=False, default=str))

    # MD report
    md_lines = [
        f"# Combined POI + Warnings GPX: {route_name}",
        "",
        f"**Route ID:** {rid}",
        f"**Status:** {summary['status']}",
        f"**Generated:** {_iso_now()}",
        "",
        "## 📊 Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Track points (unchanged) | {original_count} |",
        f"| Distance | {total_km:.2f} km |",
        f"| Warning waypoints | {len(warning_wpts)} |",
        f"| POI waypoints | {len(poi_wpts)} |",
        f"| Total waypoints added | {len(all_wpts)} |",
        f"| Geometry modified | No |",
        f"| RWGPS upload | Not performed |",
        "",
    ]

    if warning_wpts:
        md_lines.append("## ⚠️ Warning Waypoints")
        md_lines.append("")
        for w in warning_wpts:
            md_lines.append(f"- **{w['name']}** ({w['lat']:.5f}, {w['lon']:.5f}): {w['desc'][:120]}")
        md_lines.append("")

    if poi_wpts:
        md_lines.append("## 📍 POI Waypoints")
        md_lines.append("")
        for w in poi_wpts:
            md_lines.append(f"- **{w['name']}** ({w['lat']:.5f}, {w['lon']:.5f}): {w['desc'][:120]}")
        md_lines.append("")

    md_lines.append("## ❌ Skipped")
    md_lines.append("")
    if skipped_review:
        md_lines.append(f"- {skipped_review}x REVIEW (not included)")
    if skipped_suppress:
        md_lines.append(f"- {skipped_suppress}x SUPPRESS")
    if skipped_omit:
        md_lines.append(f"- {skipped_omit}x OMIT")
    if skipped_no_decision:
        md_lines.append(f"- {skipped_no_decision}x no decision")
    if skipped_poi:
        md_lines.append(f"- {skipped_poi}x POI not accepted")
    md_lines.append("")

    md_lines.append("## 💡 Import Instructions")
    md_lines.append("")
    md_lines.append("1. Open RWGPS Route Planner")
    md_lines.append("2. Import → Upload File → wybierz GPX")
    md_lines.append("3. 'Add to Planner'")
    md_lines.append("4. Save as **copy / nowa trasa** (nie nadpisuj oryginału)")
    md_lines.append("5. Pin route → Sync Hammerhead/Karoo")
    md_lines.append("")
    md_lines.append("## 🛡️ Safety")
    md_lines.append("")
    md_lines.append("- No geometry was modified")
    md_lines.append("- Only ACCEPT_WARNING segments are included")
    md_lines.append("- REVIEW/OMIT/SUPPRESS segments are excluded")
    md_lines.append("- POI included only if accepted=true")
    md_lines.append("")
    md_lines.append("---")
    md_lines.append(f"*Generated by G15 — {_iso_now()}*")

    _write(md_out, "\n".join(md_lines))

    print(f"    GPX: {gpx_out.name} ({len(warning_wpts)} warnings, {len(poi_wpts)} POI)")
    print(f"    MD:  {md_out.name}")
    print(f"    JSON: {sum_out.name}")

    return summary


def run(route_id: str) -> dict:
    rid = str(route_id)
    print(f"  Building combined GPX for {rid}...")
    result = build_combined(rid)
    if not result.get("ok"):
        print(f"  ERROR: {result.get('error')}")
        return result
    print(f"    Original trkpt: {result['original_trkpt_count']}")
    print(f"    Warnings: {result['warning_wpt_count']}, POI: {result['poi_wpt_count']}")
    print(f"    Skipped review/suppress/omit/no_decision/poi: "
          f"{result['skipped_review_count']}/{result['skipped_suppress_count']}/"
          f"{result['skipped_omit_count']}/{result['skipped_no_decision_count']}/"
          f"{result['skipped_poi_count']}")
    print(f"    Geometry modified: {result['geometry_modified']}")
    return result


def main():
    p = argparse.ArgumentParser(description="G15 Combined POI + Warnings GPX")
    p.add_argument("--route-id", required=True)
    args = p.parse_args()

    print("=" * 70)
    print("G15 Combined POI + Warnings GPX")
    print("=" * 70)
    print(f"  Route ID: {args.route_id}")
    print()

    result = run(args.route_id)
    if not result.get("ok"):
        sys.exit(1)
    print()
    print("Done.")


if __name__ == "__main__":
    main()
