-- =====================================================================
-- QBot Calendar Core v2 — ZYWY schemat kalendarza (refaktor 2026-07-16)
-- Zrzut z zywej bazy (schema qbot_v2), 2026-07-17, pg_dump --schema-only.
-- Zastepuje calendar_core_v1.sql (DEPRECATED/historyczny).
-- Tabele: calendar_entry (kolumna daty: day), calendar_day_route,
--         calendar_reminder_fired + sekwencje, klucze, indeksy, FK.
-- Triggery: BRAK na tych tabelach. Funkcja i triggery refresh_day_flags()
--           zyja osobno w sql/refresh_day_flags_fix.sql — NIE duplikowac tu.
-- Odtworzenie: psql -d qbot -f sql/calendar_core_v2.sql
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: calendar_day_route; Type: TABLE; Schema: qbot_v2; Owner: -
--

CREATE TABLE qbot_v2.calendar_day_route (
    id bigint NOT NULL,
    entry_id bigint NOT NULL,
    day date NOT NULL,
    route_id text NOT NULL,
    route_name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: calendar_day_route_id_seq; Type: SEQUENCE; Schema: qbot_v2; Owner: -
--

ALTER TABLE qbot_v2.calendar_day_route ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME qbot_v2.calendar_day_route_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calendar_entry; Type: TABLE; Schema: qbot_v2; Owner: -
--

CREATE TABLE qbot_v2.calendar_entry (
    id bigint NOT NULL,
    day date NOT NULL,
    kind text NOT NULL,
    title text,
    feel smallint,
    severity text,
    end_day date,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    color text,
    event_type text,
    at_time time without time zone,
    remind_offsets text,
    CONSTRAINT calendar_entry_kind_check CHECK ((kind = ANY (ARRAY['event'::text, 'feel'::text, 'illness'::text, 'reminder'::text])))
);


--
-- Name: calendar_entry_id_seq; Type: SEQUENCE; Schema: qbot_v2; Owner: -
--

CREATE SEQUENCE qbot_v2.calendar_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: calendar_entry_id_seq; Type: SEQUENCE OWNED BY; Schema: qbot_v2; Owner: -
--

ALTER SEQUENCE qbot_v2.calendar_entry_id_seq OWNED BY qbot_v2.calendar_entry.id;


--
-- Name: calendar_reminder_fired; Type: TABLE; Schema: qbot_v2; Owner: -
--

CREATE TABLE qbot_v2.calendar_reminder_fired (
    entry_id bigint NOT NULL,
    target_key text NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: calendar_entry id; Type: DEFAULT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_entry ALTER COLUMN id SET DEFAULT nextval('qbot_v2.calendar_entry_id_seq'::regclass);


--
-- Name: calendar_day_route calendar_day_route_entry_id_day_key; Type: CONSTRAINT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_day_route
    ADD CONSTRAINT calendar_day_route_entry_id_day_key UNIQUE (entry_id, day);


--
-- Name: calendar_day_route calendar_day_route_pkey; Type: CONSTRAINT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_day_route
    ADD CONSTRAINT calendar_day_route_pkey PRIMARY KEY (id);


--
-- Name: calendar_entry calendar_entry_pkey; Type: CONSTRAINT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_entry
    ADD CONSTRAINT calendar_entry_pkey PRIMARY KEY (id);


--
-- Name: calendar_reminder_fired calendar_reminder_fired_entry_id_target_key_key; Type: CONSTRAINT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_reminder_fired
    ADD CONSTRAINT calendar_reminder_fired_entry_id_target_key_key UNIQUE (entry_id, target_key);


--
-- Name: calendar_day_route_day_idx; Type: INDEX; Schema: qbot_v2; Owner: -
--

CREATE INDEX calendar_day_route_day_idx ON qbot_v2.calendar_day_route USING btree (day);


--
-- Name: calendar_entry_day_idx; Type: INDEX; Schema: qbot_v2; Owner: -
--

CREATE INDEX calendar_entry_day_idx ON qbot_v2.calendar_entry USING btree (day);


--
-- Name: calendar_day_route calendar_day_route_entry_id_fkey; Type: FK CONSTRAINT; Schema: qbot_v2; Owner: -
--

ALTER TABLE ONLY qbot_v2.calendar_day_route
    ADD CONSTRAINT calendar_day_route_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES qbot_v2.calendar_entry(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


